### ISSUE TITLE
 Is there a feild type?

### ISSUE THREAD

**Issue by islandryu** [dusanjovanov/formx#1]
Hi,
Thank you for creating this package.

I want a field type.
https://github.com/dusanjovanov/formx/blob/a982f49b3397e210689217ecd55ffb0552bf8580/src/Field.tsx#L123-L129

If there is no field type, could I create a pull request?

**Comment by dusanjovanov** [comment]
Hi, couldn't you pass fieldType as a prop ?

**Comment by islandryu** [comment]
Thank you for reply.

I often write like this below.
`
const TextField:FC<TextFieldProp> = ({label, field})
`
I would like to add the feild type to type.ts because it is convenient to have the feild type for when using the FC type of react.

**Comment by dusanjovanov** [comment]
Oh yeah, I thought you meant something else. Sure, open a pr .

**Comment by islandryu** [comment]
Sorry for the incomprehensible explanation...
